version: '3'
services:
  minio:
    hostname: minio
    image: 'minio/minio:RELEASE.2021-01-08T21-18-21Z'
    container_name: minio
    ports:
      - '9000:9000'
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    command: server /data
    networks:
      - minio-network


  minio-client:
    image: minio/mc
    container_name: minio-client
    depends_on:
      - minio
        ## To create Bucket with no public policy, add the following lines
        ## after configuring the host, but before "exit 0;"
        ## change "bucketnpa" to your desired bucket name
        ##
        ## /usr/bin/mc mb minio/bucketnpa;
        ## /usr/bin/mc policy none minio/bucketnpa;
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
      BUCKET_NAME: localbucket
      ENDPOINT: http://minio:9000/
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000/ minio_access_key minio_secret_key) do echo '...waiting...' && sleep 1; done;
      sleep infinity; # Keep the container running indefinitely
      exit 0;
      "
    networks:
    - minio-network


volumes: 
  minio-data:
    driver: local

networks:
  minio-network:  
    driver: bridge


